name: flux_dap
description: Debug Adapter Protocol implementation for Flux language
publish_to: none
version: 2.0.0

environment:
  sdk: ^3.6.0

dependencies:
  flux_vm:
    path: ../flux_vm
  flux_compiler:
    path: ../flux_compiler
  stream_channel: ^2.1.4
  args: ^2.6.0

dev_dependencies:
  test: ^1.28.0
  lints: ^6.0.0
