name: flux_lsp
description: Language Server Protocol implementation for Flux scripting language
publish_to: none
version: 2.0.0

environment:
  sdk: ^3.6.0

dependencies:
  flux_compiler:
    path: ../flux_compiler
  args: ^2.6.0

dev_dependencies:
  test: ^1.25.0
  lints: ^5.0.0
