name: flux_ota_example
description: Example project demonstrating Flux OTA updates.

environment:
  sdk: ^3.6.0

dependencies:
  flux_updater:
    path: ../
  flux_compiler:
    path: ../../flux_compiler

dev_dependencies:
  lints: ^5.1.1
  test: ^1.24.0
