name: flux_vm
description: The virtual machine for the Flux scripting language.
version: 0.0.1
environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flux_compiler:
    path: ../flux_compiler
  crypto: ^3.0.3
dev_dependencies:
  test: ^1.26.3
