name: flux_vm
publish_to: 'none'
description: Virtual Machine for Flux language.x scripting language.
version: 0.0.1
environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flux_compiler:
    path: ../flux_compiler
  crypto: ^3.0.3
  cryptography: ^2.9.0
dev_dependencies:
  test: ^1.26.3
